// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, gitUpdate, http, process, sys;

  express = require("express");

  http = require("http");

  sys = require("sys");

  process = require("child_process");

  app = express();

  app.configure(function() {
    return app.set("port", process.env.PORT || 3333);
  });

  gitUpdate = function(project, cb) {
    return process.exec("cd " + project + "; git pull ; npm install; bower install; cd -", cb);
  };

  app.post("/update/:csvpath", function(req, res) {
    var cb, csvpath, path;
    csvpath = req.params.csvpath;
    cb = function(error, stdout, stderr) {
      return res.send(stdout);
    };
    path = csvpath.replace(',', '/');
    return gitUpdate(path, cb);
  });

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
